# Generated by Django 5.0.6 on 2024-06-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_doc',
            new_name='product_doc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='item_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='item_price',
            new_name='product_price',
        ),
    ]
